version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get install libfftw3-dev libeigen3-dev build-essential
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools numpy cython pybind11
            pip install -r dev-requirements.txt
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install --upgrade --force-reinstall .
            flake8 pizza_cutter
            flake8 bin/pizza-cutter
            pytest -vv pizza_cutter
