version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            # patch for weirdness in mirrors - https://discuss.circleci.com/t/circleci-failing-when-using-sudo-apt-get-update/29269/9
            sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
            sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
            sudo apt-get -qq update
            sudo apt-get -qq upgrade
            sudo apt-get -qq install libfftw3-dev libeigen3-dev build-essential libcfitsio-bin
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools numpy cython pybind11
            pip install -U --progress-bar=off --upgrade-strategy=eager -r dev-requirements.txt
            pip install -U --progress-bar=off --upgrade-strategy=eager -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -U --progress-bar=off --upgrade-strategy=eager --force-reinstall -r volatile-requirements.txt
            pip install -q --progress-bar=off --force-reinstall .
            flake8 pizza_cutter
            flake8 bin

            git clone https://github.com/beckermr/des-y3-test-data.git
            export TEST_DESDATA=`pwd`/des_y3_test_data
            ls $TEST_DESDATA
            pytest -vv pizza_cutter
