version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq upgrade
            sudo apt-get -qq install libfftw3-dev libeigen3-dev build-essential libcfitsio-bin
            python3 -m venv venv
            . venv/bin/activate
            pip install -U --no-progress pip setuptools numpy cython pybind11
            pip install -U --no-progress --upgrade-strategy=eager -r dev-requirements.txt
            pip install -U --no-progress --upgrade-strategy=eager -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "volatile-requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -U --no-progress --upgrade-strategy=eager --force-reinstall -r volatile-requirements.txt
            pip install -q --no-progress --force-reinstall .
            flake8 pizza_cutter
            flake8 bin/pizza-cutter
            pytest -vv pizza_cutter
